#!/bin/bash
#
#--without-database --disable-database --with-fallbacks=xterm-256color,vt100 --without-xterm-new \
#--disable-home-terminfo --with-termlib --enable-termcap \
#

pushd ncurses
UNAME=Android \
CROSS_COMPILE=~/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21- \
CC=~/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
./configure \
--host=aarch64-linux-android21 \
\
--prefix=/foobar \
--bindir=/system/xbin \
--datadir=/system/usr/share \
--libdir=/system/lib \
--without-shared \
--without-cxx \
--without-ada \
--without-cxx-binding \
--without-manpages \
--without-progs \
--without-tack \
--without-tests \
--without-debug \
--without-profile \
--without-cxx-shared \
--without-gpm \
--without-pcre2 \
--without-sysmouse \
$*
make
popd
